GET http://localhost:5000/api/v1/transactions

###
GET http://localhost:5000/api/v1/transactions/5e579921ddb7f31858e0ee6c
###
POST http://localhost:5000/api/v1/transactions
Content-Type: application/json; charset=utf-8

{
  "text": "Foods",
  "amount": -1000
}
###
DELETE http://localhost:5000/api/v1/transactions/5e579921ddb7f31858e0ee6c
