GET http://localhost:5000/api/v1/transactions

###
GET http://localhost:5000/api/v1/transactions/5e5dfc36df70231cd4b4ca7b
###
POST http://localhost:5000/api/v1/transactions
Content-Type: application/json; charset=utf-8

{
  "text": "Foods",
  "amount": -1000
}
###
DELETE http://localhost:5000/api/v1/transactions/5e6c3f3384f17301e8a0aa56

###
PUT http://localhost:5000/api/v1/transactions/5e6c3f3384f17301e8a0aa56
Content-Type: application/json; charset=utf-8

{
  "text": "Golden amulet",
  "amount": -1000
}