GET http://localhost:5000/api/v1/transactions

###
GET http://localhost:5000/api/v1/transactions/5e5dfc36df70231cd4b4ca7b
###
POST http://localhost:5000/api/v1/transactions
Content-Type: application/json; charset=utf-8

{
  "text": "Foods",
  "amount": -1000
}
###
DELETE http://localhost:5000/api/v1/transactions/5e579921ddb7f31858e0ee6c

###
PUT http://localhost:5000/api/v1/transactions/5e65c1ff2c409621b4a7bd27
Content-Type: application/json; charset=utf-8

{
  "text": "Golden amulet",
  "amount": -1000
}